version: '3.1'

services:
  db:
    image: postgres:14.0
    ports:
      - 5432:5432
    command: postgres -c log_statement=all -c timezone='America/Mexico_City'
    volumes:
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ppassword
      
